#!/usr/bin/env tsx
/**
 * scaffold.ts
 *
 * Scaffolds a new persona research project from templates.
 * Generates:
 *   ../../output/{id}/PLAN.md       — filled Distill Plan
 *   ../../output/{id}/SKILL_TEMPLATE.md — filled SKILL.md template
 *   ../../output/{id}/triple-verify-log.md  — blank verification log
 *   ../../output/{id}/validation-log.md     — blank validation harness
 *   skills/{id}/research/triple-verify-log.md  — research archive copy
 *   skills/{id}/research/validation-log.md     — research archive copy
 *   skills/{id}/research/README.md             — research archive index
 *
 * Usage:
 *   npx tsx scripts/research/0_scaffold/scaffold.ts <persona-id> --type=HK_ENTREPRENEUR
 *   npx tsx scripts/research/0_scaffold/scaffold.ts li-ka-shing --type=CHINESE_BUSINESS
 */

import { writeFileSync, mkdirSync, existsSync, cpSync, readFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));

// ─── Persona type presets ─────────────────────────────────────────────────────

type PersonaType = "TWITTER_CRYPTO" | "CHINESE_BUSINESS" | "HK_ENTREPRENEUR" | "WESTERN_INVESTOR";

interface PersonaPreset {
  type: PersonaType;
  description: string;
  hasTwitter: boolean;
  hasBooks: boolean;
  hasLegalFilings: boolean;
  keyResearchAgents: string[];
  suggestedCategories: string[];
  deepResearchTopics: string[];
  referencePersona?: string;
}

const PRESETS: Record<string, PersonaPreset> = {
  TWITTER_CRYPTO: {
    type: "TWITTER_CRYPTO",
    description: "Crypto/trading persona with active Twitter/X presence.",
    hasTwitter: true,
    hasBooks: false,
    hasLegalFilings: true,
    keyResearchAgents: ["Agent 1", "Agent 3", "Agent 4", "Agent 5"],
    suggestedCategories: ["Crypto", "Trading", "Investing"],
    deepResearchTopics: [
      "trading methodology and market analysis approach",
      "competitive positioning vs other traders",
      "regulatory challenges and legal history",
    ],
    referencePersona: "KillaXBT",
  },
  CHINESE_BUSINESS: {
    type: "CHINESE_BUSINESS",
    description: "Chinese-language entrepreneur/business leader without Twitter.",
    hasTwitter: false,
    hasBooks: true,
    hasLegalFilings: false,
    keyResearchAgents: ["Agent 2", "Agent 4", "Agent 6"],
    suggestedCategories: ["Business", "Finance"],
    deepResearchTopics: [
      "management philosophy and organizational approach",
      "investment strategy and portfolio",
      "biography and career milestones",
    ],
    referencePersona: "Shi Yongqing",
  },
  HK_ENTREPRENEUR: {
    type: "HK_ENTREPRENEUR",
    description: "Hong Kong entrepreneur. Combines Chinese-language sources with English press.",
    hasTwitter: false,
    hasBooks: false,
    hasLegalFilings: true,
    keyResearchAgents: ["Agent 2", "Agent 4", "Agent 5", "Agent 6"],
    suggestedCategories: ["Business", "Finance", "Investing"],
    deepResearchTopics: [
      "Hong Kong real estate market analysis",
      "management philosophy and succession planning",
      "competitive dynamics and industry positioning",
    ],
    referencePersona: "Li Ka-shing",
  },
  WESTERN_INVESTOR: {
    type: "WESTERN_INVESTOR",
    description: "Western investor/business figure with English-language sources.",
    hasTwitter: false,
    hasBooks: true,
    hasLegalFilings: true,
    keyResearchAgents: ["Agent 1", "Agent 2", "Agent 4", "Agent 5", "Agent 6"],
    suggestedCategories: ["Investing", "Finance"],
    deepResearchTopics: [
      "investment philosophy and core methodology",
      "biography and formative experiences",
      "competitive landscape and key relationships",
    ],
    referencePersona: "Warren Buffett",
  },
};

// ─── Template file paths ──────────────────────────────────────────────────────

const TEMPLATES_DIR = resolve(__dirname, "../distill_templates");
const ROOT = resolve(__dirname, "../../..");

function readTemplate(name: string): string {
  const path = resolve(TEMPLATES_DIR, name);
  if (existsSync(path)) return readFileSync(path, "utf-8");
  return "";
}

// ─── File generators ──────────────────────────────────────────────────────────

function generateResearchReadme(id: string, name: string, preset: PersonaPreset): string {
  const agents = preset.keyResearchAgents.join(", ");
  const today = new Date().toISOString().slice(0, 10);
  return `# ${name} — Research Archive

> Compiled ${today}. Research type: **${preset.type}**. See [distill_templates/](../distill_templates/) for methodology.

## What's Inside

|| File | Agent | Status |
||------|-------|--------|
|| \`PLAN.md\` | Planning | Fill in before running research |
|| \`00-source-catalog.md\` | — | Auto-generated by \`pipeline.ts\` |
|| \`01-tweet-statistics.md\` | Agent 3 | \`pipeline.ts\` output (if Twitter) |
|| \`02-published-works.md\` | Agent 1 | \`pipeline.ts\` + manual |
|| \`03-interview-distillation.md\` | Agent 2 | Manual distillation |
|| \`04-adversarial.md\` | Agent 4 | Manual distillation |
|| \`05-behavioral-records.md\` | Agent 5 | Manual distillation |
|| \`06-timeline.md\` | Agent 6 | Manual distillation |
|| \`triple-verify-log.md\` | — | Triple verification evidence |
|| \`validation-log.md\` | — | Validation test results |

## Research Type

**${preset.type}** — ${preset.description}

Key research agents: ${agents}.

## Research Checklist

- [ ] Run \`npx tsx scripts/research/1_collect/pipeline.ts ${id} --type=${preset.type} --deep-research\`
- [ ] Fill in PLAN.md
- [ ] Complete Agent distillation files
- [ ] Run triple verification → \`triple-verify-log.md\`
- [ ] Run validation harness → \`validation-log.md\`
- [ ] Write SKILL.md
- [ ] Ship

## Reference Persona

${preset.referencePersona ? `See \`skills/${preset.referencePersona}/research/\` as format reference.` : "No direct reference — build from templates."}

---
*Generated by \`0_scaffold/scaffold.ts\` on ${today}*
`;
}

function generateTripleVerifyLog(id: string, name: string): string {
  return `# Triple Verification Log — ${name}

> Adapted from \`distill_templates/TRIPLE_VERIFY.md\`.
> Copy this file to \`research/triple-verify-log.md\` and fill in BEFORE writing SKILL.md §4.

**Rule:** Pass 3/3 → Mental Model. Pass 2/3 → Decision Heuristic. Pass 1/3 → Color. Pass 0/3 → Cut.

---

## The Three Tests

### Test 1 — Cross-Domain Reproduction
Same framework must surface in ≥2 different domains. One domain = coincidence. Two = pattern. Three+ = operating system.

### Test 2 — Generative Power
The model must let you predict their stance on a problem they've never addressed publicly.

### Test 3 — Non-Obvious / Exclusive
Not something any smart operator would think. Must reveal a distinctively theirs perspective.

---

## Candidate Log

|| # | Candidate model | Domain 1 | Domain 2 | T1? | Novel prediction | T2? | Who disagrees? | T3? | Verdict |
||---|---|-| - |:---:|- |:---:|- |:---:| - |
|| 1 | | | | ☐ | | ☐ | | ☐ | |
|| 2 | | | | ☐ | | ☐ | | ☐ | |
|| 3 | | | | ☐ | | ☐ | | ☐ | |
|| 4 | | | | ☐ | | ☐ | | ☐ | |
|| 5 | | | | ☐ | | ☐ | | ☐ | |
|| 6 | | | | ☐ | | ☐ | | ☐ | |
|| 7 | | | | ☐ | | ☐ | | ☐ | |
|| 8 | | | | ☐ | | ☐ | | ☐ | |
|| 9 | | | | ☐ | | ☐ | | ☐ | |
|| 10 | | | | ☐ | | ☐ | | ☐ | |

**Target:** 15–25 candidates → 3–7 Mental Models + 5–10 Heuristics.

---

## Promotion Ledger

|| Slot | Name | Candidates # | Pass count |
||------|------|------------|:-----------:|
|| Meta | | | 3/3 |
|| Model 1 | | | 3/3 |
|| Model 2 | | | 3/3 |
|| Model 3 | | | 3/3 |
|| Heuristic 1 | | | 2/3 |
|| Heuristic 2 | | | 2/3 |

---

## Anti-patterns — What NOT to promote

- Universal virtues: "work hard", "think long-term" → cut
- Single-domain quirks → heuristic at best
- Post-hoc narratives → color only
- Values statements without behavioral proof → cut

---

*Fill in for persona: ${name} (${id})*
`;
}

function generateValidationLog(id: string, name: string): string {
  return `# Validation Harness — ${name}

> Adapted from \`../distill_templates/VALIDATION_HARNESS.md\`.
> Run this BEFORE shipping. Copy to \`validation-log.md\` in the skill folder.

---

## 3+1 Protocol

### Part A — Three Known-Statement Tests

|| # | Question | Direction match? | Notes |
||---|----------|:---------------:|------|
|| 1 | | ☐ | |
|| 2 | | ☐ | |
|| 3 | | ☐ | |

**Threshold:** 2 of 3 must be directional matches.

### Part B — One Novel-Question Test

| Question | Uncertainty acknowledged? | Fabrication risk? | Verdict |
|----------|:-------------------------:|:-----------------:|---------|
| | ☐ | ☐ | Pass / Fail |

---

## Ship Gate

- [ ] 2 of 3 Part A tests pass
- [ ] Part B passes
- [ ] Changelog entry drafted
- [ ] Source catalog committed
- [ ] Triple verification log committed

---

## Results Log

|| Date | Persona | Part A | Part B | Changes |
||------|---------|:------:|:------:|---------|
|| | ${name} | | | |

---

*Fill in for persona: ${name} (${id})*
`;
}

function generateDeepResearchScript(id: string, name: string, preset: PersonaPreset): string {
  const topics = preset.deepResearchTopics.map(t => `  - "${t}"`).join("\n");
  return `#!/usr/bin/env tsx
/**
 * ${id}-deep.ts
 *
 * Persona-specific deep research for ${name} (${preset.type}).
 * Auto-generated by \`0_scaffold/scaffold.ts\`.
 *
 * Usage:
 *   npx tsx ../personas-deep-research/${id}-deep.ts
 */

import { deepResearch, scrapePage } from "../firecrawl-research.js";
import { writeFileSync, mkdirSync } from "fs";

const FIRECRAWL_KEY = process.env.VITE_FIRECRAWL_API_KEY!;

const OUT_DIR = "../../data";
mkdirSync(OUT_DIR, { recursive: true });

async function main() {
  if (!FIRECRAWL_KEY) {
    console.error("VITE_FIRECRAWL_API_KEY not set");
    process.exit(1);
  }

  console.log("🔬 Deep research for ${name}...");

  const topics = [
${topics}
  ];

  for (const topic of topics) {
    console.log(\`\\n📡 Topic: \${topic}\`);
    try {
      const result = await deepResearch(FIRECRAWL_KEY, topic, {
        recencyDays: 730,
        limit: 20,
      });
      const file = \`\${OUT_DIR}/${id}_\${topic.slice(0, 30).replace(/[^a-z]/g, "_")}.json\`;
      writeFileSync(file, JSON.stringify(result, null, 2));
      console.log(\`  ✅ Saved: \${file}\`);
    } catch (e: any) {
      console.warn(\`  ⚠️  Failed: \${e.message}\`);
    }
  }

  console.log("\\n✅ Deep research complete.");
}

main().catch(console.error);
`;
}

// ─── Main scaffold function ───────────────────────────────────────────────────

function scaffoldPersona(
  id: string,
  name: string,
  type: PersonaType
): { ok: boolean; errors: string[] } {
  const errors: string[] = [];
  const preset = PRESETS[type];
  if (!preset) {
    errors.push(`Unknown type: ${type}. Valid types: ${Object.keys(PRESETS).join(", ")}`);
    return { ok: false, errors };
  }

  const outputDir = resolve(ROOT, "../../output", id);
  const skillResearchDir = resolve(ROOT, "skills", id, "research");

  // Validate persona doesn't already exist as a fully scaffolded project
  if (existsSync(skillResearchDir)) {
    const existing = resolve(skillResearchDir, "README.md");
    if (existsSync(existing)) {
      errors.push(`skills/${id}/research/ already exists. Remove it first if you want to re-scaffold.`);
    }
  }

  if (errors.length > 0) return { ok: false, errors };

  // ── Create output directory
  mkdirSync(outputDir, { recursive: true });
  console.log(`📁 Created: ../../output/${id}/`);

  // ── Copy PLAN.md from template + fill in
  const planTemplate = readTemplate("DISTILL_PLAN.md");
  const filledPlan = planTemplate
    .replace(/\{Persona Name\}/g, name)
    .replace(/\{slug\}/g, id)
    .replace(/\{N\}/g, "—")
    .replace(/# Credit budget \(target per persona\)/, `# Credit budget (target per persona)\n\n**Type:** ${preset.type} — ${preset.description}`)
    .replace(
      /## The 6 Collection Agents.*/s,
      `## The 6 Collection Agents (${preset.keyResearchAgents.join(", ")} active)\n\n**Active agents for ${preset.type}:** ${preset.keyResearchAgents.join(", ")}.\n**Inactive agents:** ${["Agent 1", "Agent 2", "Agent 3", "Agent 4", "Agent 5", "Agent 6"].filter(a => !preset.keyResearchAgents.includes(a)).join(", ") || "none"}.`
    );
  writeFileSync(resolve(outputDir, "PLAN.md"), filledPlan);
  console.log(`✅ Created: ../../output/${id}/PLAN.md`);

  // ── Copy TRIPLE_VERIFY.md from template
  const tvTemplate = readTemplate("TRIPLE_VERIFY.md");
  const filledTv = tvTemplate.replace(/\{Persona Name\}/g, name);
  writeFileSync(resolve(outputDir, "triple-verify-log.md"), filledTv);
  console.log(`✅ Created: ../../output/${id}/triple-verify-log.md`);

  // ── Copy VALIDATION_HARNESS.md from template
  const vhTemplate = readTemplate("VALIDATION_HARNESS.md");
  const filledVh = vhTemplate.replace(/\{Persona Name\}/g, name);
  writeFileSync(resolve(outputDir, "validation-log.md"), filledVh);
  console.log(`✅ Created: ../../output/${id}/validation-log.md`);

  // ── Copy SKILL_TEMPLATE.md from template
  const skillTemplate = readTemplate("SKILL_TEMPLATE.md");
  const filledSkill = skillTemplate.replace(/\{Name\}/g, name).replace(/\{persona-slug\}/g, id);
  writeFileSync(resolve(outputDir, "SKILL_TEMPLATE.md"), filledSkill);
  console.log(`✅ Created: ../../output/${id}/SKILL_TEMPLATE.md`);

  // ── Create skill research dir with README
  mkdirSync(skillResearchDir, { recursive: true });
  writeFileSync(resolve(skillResearchDir, "README.md"), generateResearchReadme(id, name, preset));
  writeFileSync(resolve(skillResearchDir, "triple-verify-log.md"), generateTripleVerifyLog(id, name));
  writeFileSync(resolve(skillResearchDir, "validation-log.md"), generateValidationLog(id, name));
  console.log(`✅ Created: skills/${id}/research/`);

  // ── Generate deep research script
  const deepScript = generateDeepResearchScript(id, name, preset);
  const deepScriptPath = resolve(__dirname, `${id}-deep.ts`);
  writeFileSync(deepScriptPath, deepScript);
  console.log(`✅ Created: ../personas-deep-research/${id}-deep.ts`);

  return { ok: true, errors: [] };
}

// ─── CLI ─────────────────────────────────────────────────────────────────────

function parseArgs(): { id: string; name: string; type: PersonaType } {
  const args = process.argv.slice(2);
  const id = args[0]?.trim() || "";
  let name = args[1]?.trim() || id;
  let type: PersonaType = "CHINESE_BUSINESS";

  for (const arg of args) {
    if (arg.startsWith("--type=")) {
      const t = arg.split("=")[1]?.toUpperCase() as PersonaType;
      if (PRESETS[t]) type = t;
    }
    if (arg.startsWith("--name=")) name = arg.split("=")[1]?.trim() || name;
  }

  return { id, name, type };
}

function main() {
  const { id, name, type } = parseArgs();

  if (!id) {
    console.error("Usage: npx tsx 0_scaffold/scaffold.ts <persona-id> [--type=TYPE] [--name='Full Name']");
    console.error("");
    console.error("Types:");
    for (const [key, val] of Object.entries(PRESETS)) {
      console.error(`  ${key.padEnd(20)} ${val.description}`);
    }
    console.error("");
    console.error("Examples:");
    console.error("  npx tsx 0_scaffold/scaffold.ts li-ka-shing --type=HK_ENTREPRENEUR --name='Li Ka-shing 李嘉誠'");
    console.error("  npx tsx 0_scaffold/scaffold.ts warren-buffett --type=WESTERN_INVESTOR --name='Warren Buffett'");
    console.error("  npx tsx 0_scaffold/scaffold.ts killa-xbt --type=TWITTER_CRYPTO --name='KillaXBT'");
    process.exit(1);
  }

  console.log(`\n🚀 Scaffolding persona research: ${name} (${id})`);
  console.log(`   Type: ${type}`);
  console.log("");

  const result = scaffoldPersona(id, name, type);

  if (!result.ok) {
    console.error("\n❌ Errors:");
    for (const e of result.errors) console.error(`   - ${e}`);
    process.exit(1);
  }

  console.log("\n" + "=".repeat(60));
  console.log(`  ✅ Scaffolding complete: ${id}`);
  console.log("=".repeat(60));
  console.log("");
  console.log("Next steps:");
  console.log(`  1. npx tsx ../1_collect/pipeline.ts ${id} --type=${type} --deep-research`);
  console.log(`  2. Edit ../../output/${id}/PLAN.md`);
  console.log(`  3. Run distillation → fill in triple-verify-log.md`);
  console.log(`  4. npx tsx ../3_validate/validation-runner.ts ${id}`);
  console.log(`  5. Write skills/${id}/SKILL.md`);
  console.log("");
}

main();
