#!/usr/bin/env tsx
/**
 * triple-verify-runner.ts
 *
 * Auto-populates triple-verify-log.md from persona data in personas.ts.
 * Reads mentalModels[] from the persona and pre-fills the candidate log
 * so you only need to add the cross-domain evidence and verdict.
 *
 * Usage:
 *   npx tsx scripts/research/2_distill/triple-verify-runner.ts <persona-id>
 *   npx tsx scripts/research/2_distill/triple-verify-runner.ts elon-musk --dry-run
 */

import { createRequire } from "module";
import { resolve } from "path";
import { writeFileSync } from "fs";
import { getScriptDir, resolveProjectRoot } from "./path-utils.js";

const SCRIPT_DIR = getScriptDir();
const ROOT = resolveProjectRoot(SCRIPT_DIR);
const PERSONAS_PATH = resolve(ROOT, "src/lib/personas.ts");
const SKILLS_DIR = resolve(ROOT, "skills");

// ─── Types ─────────────────────────────────────────────────────────────────────

interface Persona {
  id: string; name: string;
  mentalModels?: { name: string; origin: string; trigger: string; internalMonologue: string; output: string; confidence: string }[];
  decisionHeuristics?: { name: string; scenario: string; example: string }[];
}

// ─── Load persona ───────────────────────────────────────────────────────────────

function loadPersona(id: string): Persona | null {
  const require = createRequire(import.meta.url);
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const mod = require(PERSONAS_PATH) as any;
  const personas: Persona[] = mod.personas ?? mod.default ?? mod;
  if (!Array.isArray(personas)) return null;
  return personas.find(p => p.id === id) ?? null;
}

// ─── Candidate log generator ───────────────────────────────────────────────────

function buildCandidateLog(p: Persona): string {
  const MAX_CANDIDATES = 20;
  const lines: string[] = [];
  lines.push("||| # | Candidate model | Domain 1 evidence | Domain 2 evidence | Domain 3 evidence | T1? | Novel prediction enabled | T2? | Who would disagree? | T3? | Verdict |");
  lines.push("|||---|-----------------|------------------|------------------|------------------|:----:|--------------------------|:----:|--------------------|:----:|-----|");
  const models = (p.mentalModels ?? []).slice(0, MAX_CANDIDATES);
  for (let i = 0; i < MAX_CANDIDATES; i++) {
    const m = models[i];
    if (m) {
      lines.push(`||| ${i + 1} | ${m.name} | > "${m.origin.slice(0, 80)}..." | > "${m.trigger.slice(0, 60)}..." | ${m.internalMonologue.slice(0, 60)}... | ☐ | ${m.output.slice(0, 80)}... | ☐ | {competitor name} | ☐ | Model / Heuristic / Cut |`);
    } else {
      lines.push(`||| ${i + 1} | | | | | ☐ | | ☐ | | ☐ | |`);
    }
  }
  return lines.join("\n");
}

function buildPromotionLedger(p: Persona): string {
  const lines: string[] = [];
  lines.push("||| Slot | Name | Candidate # | Pass count | Notes |");
  lines.push("|||------|------|------------|:-----------:|-------|");
  lines.push("||| Meta | | | 3/3 | |");
  for (let i = 0; i < Math.min(p.mentalModels?.length ?? 0, 7); i++) {
    lines.push(`||| Model ${i + 1} | | | 3/3 | |`);
  }
  if (p.decisionHeuristics) {
    for (let i = 0; i < Math.min(p.decisionHeuristics.length, 5); i++) {
      lines.push(`||| Heuristic ${i + 1} | | | 2/3 | |`);
    }
  }
  return lines.join("\n");
}

function generateTripleVerifyLog(p: Persona): string {
  return `# Triple Verification Log — ${p.name}

> Adapted from \`distill_templates/TRIPLE_VERIFY.md\`.
> Auto-populated from \`personas.ts\` mental models. Fill in the test columns (☐ → ✅/❌) before writing SKILL.md §4.

**Rule:** Pass 3/3 → Mental Model. Pass 2/3 → Decision Heuristic. Pass 1/3 → Color. Pass 0/3 → Cut.

---

## The Three Tests

### Test 1 — Cross-Domain Reproduction
Same framework must surface in ≥2 different domains of the subject's life (e.g., business + philosophy + investing). One domain = coincidence. Two = pattern. Three+ = operating system.

### Test 2 — Generative Power
The model must let you predict their stance on a problem they've never addressed publicly.

### Test 3 — Non-Obvious / Exclusive
Not something any smart operator would think. Must reveal a distinctively theirs perspective that a thoughtful competitor would disagree with.

---

## Candidate Log

${buildCandidateLog(p)}

**Target:** 15–25 candidates → 3–7 Mental Models + 5–10 Heuristics.

---

## Promotion Ledger

${buildPromotionLedger(p)}

---

## Anti-patterns — What NOT to promote

- Universal virtues: "work hard", "think long-term" → cut
- Single-domain quirks → heuristic at best
- Post-hoc narratives → color only
- Values statements without behavioral proof → cut

---

## Review Cadence

Re-run triple verification **every 6 months** for active personas.

---

*Auto-generated by \`scripts/research/2_distill/triple-verify-runner.ts\`*
`;
}

// ─── CLI ─────────────────────────────────────────────────────────────────────

function main() {
  const args = process.argv.slice(2);
  const dryRun = args.includes("--dry-run");
  const id = args.find(a => !a.startsWith("--"));

  if (!id) {
    console.error("Usage: npx tsx scripts/research/2_distill/triple-verify-runner.ts <persona-id>");
    console.error("  npx tsx scripts/research/2_distill/triple-verify-runner.ts elon-musk --dry-run");
    process.exit(1);
  }

  console.log(`\n🔍 Triple Verify Runner: ${id}${dryRun ? " [DRY RUN]" : ""}`);

  const p = loadPersona(id);
  if (!p) {
    console.error(`❌ Persona "${id}" not found in personas.ts`);
    process.exit(1);
  }

  console.log(`  Found: ${p.name}`);
  console.log(`  Mental models: ${p.mentalModels?.length ?? 0}`);
  console.log(`  Decision heuristics: ${p.decisionHeuristics?.length ?? 0}`);

  const content = generateTripleVerifyLog(p);
  const outPath = resolve(SKILLS_DIR, id, "research", "triple-verify-log.md");

  if (dryRun) {
    console.log(`\n  [DRY RUN] Would write to: ${outPath.replace(ROOT + "/", "")}`);
    console.log("\n  Preview (first 60 lines):");
    console.log("─".repeat(50));
    content.split("\n").slice(0, 60).forEach(l => console.log("  " + l));
    return;
  }

  writeFileSync(outPath, content);
  console.log(`\n✅ Written: skills/${id}/research/triple-verify-log.md`);
}

main();
